name: Bug report
description: Report a bug.
title: "Bug: "
body:
  - type: markdown
    attributes:
      value: |
        **Finding a solution before reporting something**
        Before creating a new issue, I recommend:  
        - updating to the latest version,
        - searching for related issues and solutions here,
        - and checking relevant channels on the Discord server.
  - type: dropdown
    attributes:
      label: Type
      options:
        - VEGAS Pro crash
        - Performance
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your problem
      description: A clear description of what the issue is.
      placeholder: ex. VEGAS crashed after I clicked X and Y.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the issue
      placeholder: |
        1. Click on '...'
        2. Change '...'
        3. See error '...'
  - type: textarea
    attributes:
      label: Screenshots or video
      description: Add screenshots or videos that show the bug.
      placeholder: Drag and drop the screenshots/videos into this box.
  - type: input
    attributes:
      label: VPFlow version
      description: The version you encountered this bug on.
    validations:
      required: true
  - type: input
    attributes:
      label: VEGAS Pro version
    validations:
      required: true
  - type: input
    attributes:
      label: Windows version
    validations:
      required: true
